name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool pkg-config

    # Configure the build
    - name: Run configure
      run: |
        if [ -f ./configure ]; then
          ./configure
        else
          echo "No configure script found. Ensure it exists and is executable."
          exit 1
        fi

    # Build the project
    - name: Build project
      run: make

    # Run tests
    - name: Run tests
      run: make check

    # Verify distribution integrity
    - name: Run distcheck
      run: make distcheck
